### ISSUE TITLE
SIBR viewer compiling error

### ISSUE THREAD

**Issue by brianneoberson** [oppo-us-research/SpacetimeGaussians#45]
Hello, 

I've trained one of the Neural3D scenes and want to inspect the results using the SIBR viewer. I followed the instructions in the comments of `script/setup.sh` but after replacing the two folders mentioned in the instructions and running `cmake --build build --target install --config RelWithDebInfo` I get the following error:

```
[ 95%] Building CXX object src/projects/gaussianviewer/renderer/CMakeFiles/sibr_gaussian.dir/GaussianView.cpp.o
/media/dc-04-vol03/Brianne/HBR/gaussian-splatting/SIBR_viewers/src/projects/gaussianviewer/renderer/GaussianView.cpp: In member function ‘virtual void sibr::GaussianView::onRenderIBR(sibr::IRenderTarget&, const sibr::Camera&)’:
/media/dc-04-vol03/Brianne/HBR/gaussian-splatting/SIBR_viewers/src/projects/gaussianviewer/renderer/GaussianView.cpp:635:52: error: no matching function for call to ‘CudaRasterizer::Rasterizer::forward(std::function<char*(long unsigned int)>&, std::function<char*(long unsigned int)>&, std::function<char*(long unsigned int)>&, int&, int&, int, float&, float*&, float*&, float*&, float*&, float*&, float*&, float*&, float*&, Eigen::DenseCoeffsBase<Eigen::Matrix<int, 2, 1, 2>, 1>::Scalar&, Eigen::DenseCoeffsBase<Eigen::Matrix<int, 2, 1, 2>, 1>::Scalar&, std::nullptr_t, float*&, float*&, float&, float*&, float*&, float*&, std::nullptr_t, float*&, float*&, float*&, float&, float&, bool, float*&, std::nullptr_t, int*&, float*&, float*&)’
  635 |                 CudaRasterizer::Rasterizer::forward(
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
  636 |                         geomBufferFunc,
      |                         ~~~~~~~~~~~~~~~             
  637 |                         binningBufferFunc,
      |                         ~~~~~~~~~~~~~~~~~~          
  638 |                         imgBufferFunc,
      |                         ~~~~~~~~~~~~~~              
  639 |                         count, _sh_degree, 16,
      |                         ~~~~~~~~~~~~~~~~~~~~~~      
  640 |                         timestamp,
      |                         ~~~~~~~~~~                  
  641 |                         trbfcenter_cuda,
      |                         ~~~~~~~~~~~~~~~~            
  642 |                         trbfscale_cuda,
      |                         ~~~~~~~~~~~~~~~             
  643 |                         motion_cuda,
      |                         ~~~~~~~~~~~~                
  644 |                         pos_cuda,
      |                         ~~~~~~~~~                   
  645 |                         means3Ddummy_cuda,
      |                         ~~~~~~~~~~~~~~~~~~          
  646 |                         opacity_cuda,
      |                         ~~~~~~~~~~~~~               
  647 |                         opacitiesdummy_cuda,
      |                         ~~~~~~~~~~~~~~~~~~~~        
  648 |                         background_cuda,
      |                         ~~~~~~~~~~~~~~~~            
  649 |                         _resolution.x(), _resolution.y(),
      |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  650 |                         nullptr,
      |                         ~~~~~~~~                    
  651 |                         colors_precomp_cuda,
      |                         ~~~~~~~~~~~~~~~~~~~~        
  652 |                         scale_cuda,
      |                         ~~~~~~~~~~~                 
  653 |                         _scalingModifier,
      |                         ~~~~~~~~~~~~~~~~~           
  654 |                         rot_cuda,
      |                         ~~~~~~~~~                   
  655 |                         rott_cuda,
      |                         ~~~~~~~~~~                  
  656 |                         rotdummy_cuda,
      |                         ~~~~~~~~~~~~~~              
  657 |                         nullptr,
      |                         ~~~~~~~~                    
  658 |                         view_cuda,
      |                         ~~~~~~~~~~                  
  659 |                         proj_cuda,
      |                         ~~~~~~~~~~                  
  660 |                         cam_pos_cuda,
      |                         ~~~~~~~~~~~~~               
  661 |                         tan_fovx,
      |                         ~~~~~~~~~                   
  662 |                         tan_fovy,
      |                         ~~~~~~~~~                   
  663 |                         false,
      |                         ~~~~~~                      
  664 |                         image_cuda,
      |                         ~~~~~~~~~~~                 
  665 |                         nullptr,
      |                         ~~~~~~~~                    
  666 |                         rects,
      |                         ~~~~~~                      
  667 |                         boxmin,
      |                         ~~~~~~~                     
  668 |                         boxmax
      |                         ~~~~~~                      
  669 |                 );
      |                 ~                                   
In file included from /media/dc-04-vol03/Brianne/HBR/gaussian-splatting/SIBR_viewers/src/projects/gaussianviewer/renderer/GaussianView.cpp:16:
/media/dc-04-vol03/Brianne/HBR/gaussian-splatting/SIBR_viewers/extlibs/CudaRasterizer/CudaRasterizer/cuda_rasterizer/rasterizer.h:31:28: note: candidate: ‘static int CudaRasterizer::Rasterizer::forward(std::function<char*(long unsigned int)>, std::function<char*(long unsigned int)>, std::function<char*(long unsigned int)>, int, int, int, const float*, int, int, const float*, const float*, const float*, const float*, const float*, float, const float*, const float*, const float*, const float*, const float*, float, float, bool, float*, int*, int*, float*, float*)’
   31 |                 static int forward(
      |                            ^~~~~~~
/media/dc-04-vol03/Brianne/HBR/gaussian-splatting/SIBR_viewers/extlibs/CudaRasterizer/CudaRasterizer/cuda_rasterizer/rasterizer.h:31:28: note:   candidate expects 28 arguments, 36 provided
gmake[2]: *** [src/projects/gaussianviewer/renderer/CMakeFiles/sibr_gaussian.dir/build.make:90: src/projects/gaussianviewer/renderer/CMakeFiles/sibr_gaussian.dir/GaussianView.cpp.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1700: src/projects/gaussianviewer/renderer/CMakeFiles/sibr_gaussian.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

Would you have any suggestions to fix this problem? I'm not sure if I missed a step or if there is a problem with the CudaRasterizer code.

**Comment by lizhan17** [comment]
did you install on windows ? we only test the viewer on windows. 

if you replace files, there should a hidden .git in the original folder, please do not replace that .git folder.

**Comment by brianneoberson** [comment]
Thanks for the quick response!
I indeed made sure not to replace the gaussian_splatting/SIBR_viewers/.git file. 
But I am not using windows, I am on Linux. Is there no way to make it work on Linux?

**Comment by brianneoberson** [comment]
yes, that is what I did. I am building on Linux after replacing the files mentioned. But I get the error as showed above...

**Comment by brianneoberson** [comment]
I'm not sure what went wrong the first time, but I tried cloning the gaussian-splatting repo again and replacing the two folders again. The build was successful this time. :)

**Comment by szat** [comment]
@brianneoberson would it be possible to provide a small install tutorial for linux?

**Comment by szat** [comment]
I keep getting this error, anyone has any ideas?

```
Consolidate compiler generated dependencies of target SIBR_gaussianViewer_app
[ 95%] Linking CXX executable SIBR_gaussianViewer_app
/usr/bin/ld: ../../renderer/libsibr_gaussian.so: undefined reference to `CudaRasterizer::Rasterizer::forward(std::function<char* (unsigned long)>, std::function<char* (unsigned long)>, std::function<char* (unsigned long)>, int, int, int, float const*, int, int, float const*, float const*, float const*, float const*, float const*, float, float const*, float const*, float const*, float const*, float const*, float, float, bool, float*, int*, int*, float*, float*)'
collect2: error: ld returned 1 exit status
gmake[2]: *** [src/projects/gaussianviewer/apps/gaussianViewer/CMakeFiles/SIBR_gaussianViewer_app.dir/build.make:189: src/projects/gaussianviewer/apps/gaussianViewer/SIBR_gaussianViewer_app] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:1609: src/projects/gaussianviewer/apps/gaussianViewer/CMakeFiles/SIBR_gaussianViewer_app.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
```

**Comment by Egolee0713** [comment]
@szat  I met the same problem. Have you solved it?

**Comment by Nielsencu** [comment]
from thirdparty/gaussian-splatting/SIBR_viewers, I ran:
rsync -auv --exclude='*.git*' ../../gaussian_splatting/realtimedemolite/CudaRasterizer extlibs/

as for the projects directory,
cp -r ../../gaussian_splatting/realtimedemolite/projects/ src/projects

**Comment by studkf** [comment]
Thank you all for your excellent suggestions, but after testing, none of them worked on my `Ubuntu22.04` machine. Then I found that the problem appeared in the `thirdparty/gaussian_splatting/realtimedemolite/projects/gaussianviewer/renderer/CMakeLists.txt` file, When the `cmake -Bbuild.` command was executed for the second time, the `sibr_gitlibrary` function in the `CMakeLists.txt` file was executed, overwriting some files in the `CudaRasterizer` folder that we had previously copied over. So as to make the `CudaRasterizer: : Rasterizer: : forward` can't be matched. Therefore, the solution is also relatively simple. You can modify part of the content of the `CMakeLists.txt` file under the `projects` folder:
1. Delete or comment out the following code
```
sibr_gitlibrary(TARGET CudaRasterizer
    GIT_REPOSITORY 	"https://github.com/graphdeco-inria/diff-gaussian-rasterization.git"
    GIT_TAG			"3509be80f83ee30599b23bb3542d45aea2174a03"
)
```
2. Add the following two lines of code below the original `sibr_gitlibrary` function 
```
set(CudaRasterizer_SOURCE_DIR "${CMAKE_SOURCE_DIR}/extlibs/CudaRasterizer/CudaRasterizer")
set(CudaRasterizer_BUILD_DIR "${CMAKE_SOURCE_DIR}/extlibs/CudaRasterizer/build")
```
3. Add the following code under `add_library(${PROJECT_NAME} SHARED ${SOURCES})`
```
add_subdirectory(${CudaRasterizer_SOURCE_DIR} ${CudaRasterizer_BUILD_DIR})
```
If you are confused about the above description, it might be because I haven't explained it clearly enough. In that case, you can directly look at the complete code below.
```
# Copyright (C) 2023, Inria
# GRAPHDECO research group, https://team.inria.fr/graphdeco
# All rights reserved.
# 
# This software is free for non-commercial, research and evaluation use 
# under the terms of the LICENSE.md file.
# 
# For inquiries contact sibr@inria.fr and/or George.Drettakis@inria.fr

set(SIBR_PROJECT "gaussian")
project(sibr_${SIBR_PROJECT} LANGUAGES CXX)

# sibr_gitlibrary(TARGET CudaRasterizer
#     GIT_REPOSITORY 	"https://github.com/graphdeco-inria/diff-gaussian-rasterization.git"
#     GIT_TAG			"3509be80f83ee30599b23bb3542d45aea2174a03"
# )
set(CudaRasterizer_SOURCE_DIR "${CMAKE_SOURCE_DIR}/extlibs/CudaRasterizer/CudaRasterizer")
set(CudaRasterizer_BUILD_DIR "${CMAKE_SOURCE_DIR}/extlibs/CudaRasterizer/build")

find_package(CUDAToolkit REQUIRED)

file(GLOB SOURCES "*.cpp" "*.h" "*.hpp")
source_group("Source Files" FILES ${SOURCES})

file(GLOB SHADERS "shaders/*.frag" "shaders/*.vert" "shaders/*.geom")
source_group("Source Files\\shaders" FILES ${SHADERS})

file(GLOB SOURCES "*.cpp" "*.h" "*.hpp" "shaders/*.frag" "shaders/*.vert" "shaders/*.geom")

## Specify target rules
add_library(${PROJECT_NAME} SHARED ${SOURCES})
add_subdirectory(${CudaRasterizer_SOURCE_DIR} ${CudaRasterizer_BUILD_DIR})

include_directories(${Boost_INCLUDE_DIRS} .)
if (WIN32)
target_link_libraries(${PROJECT_NAME}
	${Boost_LIBRARIES}
	${ASSIMP_LIBRARIES}
	${GLEW_LIBRARIES}
	${OPENGL_LIBRARIES}
	${OpenCV_LIBRARIES}
	glfw3
	sibr_system
	sibr_view
	sibr_assets
	sibr_renderer
	sibr_basic
	CUDA::cudart
	CudaRasterizer
)
else()
target_link_libraries(${PROJECT_NAME}
	${Boost_LIBRARIES}
	${ASSIMP_LIBRARIES}
	${GLEW_LIBRARIES}
	${OPENGL_LIBRARIES}
	${OpenCV_LIBRARIES}
	glfw
	sibr_system
	sibr_view
	sibr_assets
	sibr_renderer
	sibr_basic
	CUDA::cudart
	CudaRasterizer
)
endif()

add_definitions( -DSIBR_EXP_ULR_EXPORTS -DBOOST_ALL_DYN_LINK  )

set_target_properties(${PROJECT_NAME} PROPERTIES FOLDER "projects/${SIBR_PROJECT}/renderer")

## High level macro to install in an homogen way all our ibr targets
include(install_runtime)
ibr_install_target(${PROJECT_NAME}
    INSTALL_PDB                         ## mean install also MSVC IDE *.pdb file (DEST according to target type)
	SHADERS ${SHADERS}
	RSC_FOLDER ${SIBR_PROJECT}

    #STANDALONE  ${INSTALL_STANDALONE}   ## mean call install_runtime with bundle dependencies resolution
    COMPONENT   ${PROJECT_NAME}_install ## will create custom target to install only this project
)
```
After completing the above steps and recompiling with `cmake -Bbuild .`, a `warning` will appear. This is because the `thirdparty gaussian_splatting/realtimedemolite/CudaRasterizer/CudaRasterizer/CMakeLists.txt` file `set_target_properties(CudaRasterizer PROPERTIES CUDA_ARCHITECTURES "70;75;86")` has carried on the annotation, it is ok to open it.
After the above operations, `SIBR Viewer` can be compiled and work.
